image: ghcr.io/lescai-teaching/rstudio-bio-jupyter:latest

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - name: rstudio
    port: 8787
    onOpen: open-browser

tasks:
  - init: |
      sudo rstudio-server start
  - command: |
        export PATH="$PATH:/usr/local/bin"
        cd
        source .bashrc
        sleep 5000
